Repository Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris, pull requests merged in 2020-10, with the labels that each got.

#17 #09 Perfil de usuário
  docs/_sidebar.md
  docs/img/questionario/questionario_01.png
  docs/img/questionario/questionario_02.png
  docs/img/questionario/questionario_03.png
  docs/img/questionario/questionario_04.png
  docs/img/questionario/questionario_05.png
  docs/img/questionario/questionario_06.png
  docs/img/questionario/questionario_07.png
  docs/img/questionario/questionario_08.png
  docs/img/questionario/questionario_09.png
  docs/img/questionario/questionario_10.png
  docs/img/questionario/questionario_11.png
  docs/img/questionario/questionario_12.png
  docs/img/questionario/questionario_13.png
  docs/img/questionario/questionario_14.png
  docs/img/questionario/questionario_15.png
  docs/perfil_de_usuario.md
Labels: Ponto de controle 1, documentation

#18 #13 Cronograma
  docs/img/cronograma.png
  docs/img/cronograma/cronograma.png
  docs/img/cronograma/cronograma_0.png
  docs/img/cronograma/cronograma_1.png
  docs/img/cronograma/cronograma_2.png
  docs/img/cronograma/cronograma_3.png
  docs/img/cronograma/cronograma_4.png
  docs/img/cronograma/cronograma_5.png
  docs/img/cronograma/cronograma_6.png
  docs/planejamento.md
Labels: correção, documentation, hacktoberfest-accepted

#19 10 personas
  docs/_sidebar.md
  docs/img/personas/Luiza.jpeg
  docs/img/personas/Roberto.jpeg
  docs/img/personas/Sara.jpeg
  docs/img/personas/joao.png
  docs/img/personas/jose.png
  docs/img/personas/veronica.jpg
  docs/personas.md
Labels: Ponto de controle 1, documentation, hacktoberfest-accepted

#20 #11 analise de tarefas
  docs/_sidebar.md
  docs/analise_de_requisitos/analise_de_tarefas.md
  docs/analise_de_requisitos/perfil_de_usuario.md
  docs/analise_de_requisitos/personas.md
  docs/img/tarefas/contas_publicas_diagrama.png
  docs/img/tarefas/covid_diagrama.png
  docs/img/tarefas/noticias_recentes_diagrama.png
  docs/personas.md
Labels: Ponto de controle 1, documentation, hacktoberfest-accepted

#22 Bug Imagem Personas
  docs/analise_de_requisitos/personas.md
Labels: bug, hacktoberfest-accepted

#24 #14 Processo de design
  docs/planejamento.md
Labels: correção, documentation

#26 Apresentação do Ponto de Controle 1
  docs/_sidebar.md
  docs/analise_de_requisitos/apresentacao.md
Labels: Ponto de controle 1, apresentação

#33 Corrige bug em imagens
  docs/analise_de_requisitos/personas.md
Labels: bug

#35 #29 Metas de Usabilidade
  docs/_sidebar.md
  docs/analise_de_requisitos/metas_usabilidade.md
Labels: documentation, hacktoberfest-accepted, ponto de controle 2

#34 #28 Princípios gerais de projeto
  docs/_sidebar.md
  docs/analise_de_requisitos/principios.md
Labels: documentation, hacktoberfest-accepted, ponto de controle 2

#36 30 guia de estilo
  docs/_sidebar.md
  docs/analise_de_requisitos/guia_de_estilo.md
  docs/img/guia_de_estilo/brasao.png
  docs/img/guia_de_estilo/cores.png
  docs/img/guia_de_estilo/icone_de_atencao.png
  docs/img/guia_de_estilo/icone_de_erro.png
  docs/img/guia_de_estilo/icone_de_sucesso.png
  docs/img/guia_de_estilo/janelas.png
  docs/img/guia_de_estilo/pagina_inicial.png
Labels: documentation, enhancement, hacktoberfest-accepted, ponto de controle 2

#39 #37 storyboard
  docs/_sidebar.md
  docs/apresentacoes/apresentacao.md
  docs/apresentacoes/apresentacao2.md
  docs/design_avaliacao_desenvolvimento/storyboard.md
  docs/img/storyboard/storyboard_contas_1.png
  docs/img/storyboard/storyboard_contas_2.png
  docs/img/storyboard/storyboard_covid_1.png
  docs/img/storyboard/storyboard_covid_2.png
  docs/img/storyboard/storyboard_noticias_1.png
  docs/img/storyboard/storyboard_noticias_2.png
Labels: documentation, hacktoberfest-accepted

#40 #38 Planejamento avaliação do storyboard
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/planejamento_avaliacao_storyboard.md
Labels: documentation, hacktoberfest-accepted

#42 41 avaliacao storyboard
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/avaliacao_storyboard.md
Labels: documentation, hacktoberfest-accepted
