Repository Interacao-Humano-Computador/2020.1-Prefeitura-Municipal-de-Arco-Iris, pull requests merged in 2020-11, with the labels that each got.

#45 #33 Apresentação 3
  docs/_sidebar.md
  docs/apresentacoes/apresentacao3.md
Labels: apresentação, hacktoberfest-accepted

#47 46 corrigir imagens quebradas
  docs/analise_de_requisitos/img/personas/Luiza.jpeg
  docs/analise_de_requisitos/img/personas/Roberto.jpeg
  docs/analise_de_requisitos/img/personas/Sara.jpeg
  docs/analise_de_requisitos/img/personas/joao.png
  docs/analise_de_requisitos/img/personas/jose.png
  docs/analise_de_requisitos/img/personas/veronica.jpg
  docs/analise_de_requisitos/personas.md
Labels: correção, documentation, hacktoberfest-accepted

#49 #48 Planejamento avaliação protótipo papel
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/planejamento_avaliacao_prototipoPapel.md
Labels: documentation

#54 51 prototipo de papel
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/img/contas_publicas_dropdown.jpeg
  docs/design_avaliacao_desenvolvimento/img/coronavirus.jpeg
  docs/design_avaliacao_desenvolvimento/img/noticias.jpeg
  docs/design_avaliacao_desenvolvimento/img/pagina_inicial.jpeg
  docs/design_avaliacao_desenvolvimento/img/prestacao_contas_publicas.jpeg
  docs/design_avaliacao_desenvolvimento/prototipo_em_papel.md
Labels: documentation

#52 #50 Termo de consentimento
  docs/design_avaliacao_desenvolvimento/termo_de_consentimento.md
Labels: documentation

#55 #53 refatorar ponto controle 3
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/analise_tarefas/avaliacao_analise_de_tarefas.md
  docs/design_avaliacao_desenvolvimento/analise_tarefas/entrevista_tarefas.md
  docs/design_avaliacao_desenvolvimento/analise_tarefas/planejamento_avaliacao_analise_tarefas.md
  docs/design_avaliacao_desenvolvimento/planejamento_avaliacao_storyboard.md
  docs/design_avaliacao_desenvolvimento/prototipo_baixa_fidelidade/planejamento_avaliacao_prototipoPapel.md
  docs/design_avaliacao_desenvolvimento/prototipo_baixa_fidelidade/prototipo_em_papel.md
  docs/design_avaliacao_desenvolvimento/prototipo_baixa_fidelidade/termo_de_consentimento.md
  docs/design_avaliacao_desenvolvimento/storyboard/avaliacao_storyboard.md
  docs/design_avaliacao_desenvolvimento/storyboard/planejamento_avaliacao_storyboard.md
  docs/design_avaliacao_desenvolvimento/storyboard/storyboard.md
  docs/img/prototipo_em_papel/contas_publicas_dropdown.jpeg
  docs/img/prototipo_em_papel/coronavirus.jpeg
  docs/img/prototipo_em_papel/noticias.jpeg
  docs/img/prototipo_em_papel/pagina_inicial.jpeg
  docs/img/prototipo_em_papel/prestacao_contas_publicas.jpeg
Labels: correção, documentation

#59 Define planejamento do prototipo de alta fidelidade
  docs/_sidebar.md
  docs/design_avaliacao_desenvolvimento/prototipo_alta_fidelidade/planejamento_avaliacao_prototipoAltaFidelidade.md
Labels: documentation
